/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicElksVoiceStartRouteImport } from './routes/api/public/elks-voice-start'
import { Route as ApiPublicElksTestRouteImport } from './routes/api/public/elks-test'
import { Route as ApiPublicElksStatusRouteImport } from './routes/api/public/elks-status'
import { Route as ApiPublicElksCancelOngoingRouteImport } from './routes/api/public/elks-cancel-ongoing'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElksVoiceStartRoute = ApiPublicElksVoiceStartRouteImport.update({
  id: '/api/public/elks-voice-start',
  path: '/api/public/elks-voice-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElksTestRoute = ApiPublicElksTestRouteImport.update({
  id: '/api/public/elks-test',
  path: '/api/public/elks-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElksStatusRoute = ApiPublicElksStatusRouteImport.update({
  id: '/api/public/elks-status',
  path: '/api/public/elks-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElksCancelOngoingRoute =
  ApiPublicElksCancelOngoingRouteImport.update({
    id: '/api/public/elks-cancel-ongoing',
    path: '/api/public/elks-cancel-ongoing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/public/elks-cancel-ongoing': typeof ApiPublicElksCancelOngoingRoute
  '/api/public/elks-status': typeof ApiPublicElksStatusRoute
  '/api/public/elks-test': typeof ApiPublicElksTestRoute
  '/api/public/elks-voice-start': typeof ApiPublicElksVoiceStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/public/elks-cancel-ongoing': typeof ApiPublicElksCancelOngoingRoute
  '/api/public/elks-status': typeof ApiPublicElksStatusRoute
  '/api/public/elks-test': typeof ApiPublicElksTestRoute
  '/api/public/elks-voice-start': typeof ApiPublicElksVoiceStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/public/elks-cancel-ongoing': typeof ApiPublicElksCancelOngoingRoute
  '/api/public/elks-status': typeof ApiPublicElksStatusRoute
  '/api/public/elks-test': typeof ApiPublicElksTestRoute
  '/api/public/elks-voice-start': typeof ApiPublicElksVoiceStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/kanban'
    | '/login'
    | '/settings'
    | '/api/public/elks-cancel-ongoing'
    | '/api/public/elks-status'
    | '/api/public/elks-test'
    | '/api/public/elks-voice-start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/kanban'
    | '/login'
    | '/settings'
    | '/api/public/elks-cancel-ongoing'
    | '/api/public/elks-status'
    | '/api/public/elks-test'
    | '/api/public/elks-voice-start'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/kanban'
    | '/login'
    | '/settings'
    | '/api/public/elks-cancel-ongoing'
    | '/api/public/elks-status'
    | '/api/public/elks-test'
    | '/api/public/elks-voice-start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicElksCancelOngoingRoute: typeof ApiPublicElksCancelOngoingRoute
  ApiPublicElksStatusRoute: typeof ApiPublicElksStatusRoute
  ApiPublicElksTestRoute: typeof ApiPublicElksTestRoute
  ApiPublicElksVoiceStartRoute: typeof ApiPublicElksVoiceStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elks-voice-start': {
      id: '/api/public/elks-voice-start'
      path: '/api/public/elks-voice-start'
      fullPath: '/api/public/elks-voice-start'
      preLoaderRoute: typeof ApiPublicElksVoiceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elks-test': {
      id: '/api/public/elks-test'
      path: '/api/public/elks-test'
      fullPath: '/api/public/elks-test'
      preLoaderRoute: typeof ApiPublicElksTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elks-status': {
      id: '/api/public/elks-status'
      path: '/api/public/elks-status'
      fullPath: '/api/public/elks-status'
      preLoaderRoute: typeof ApiPublicElksStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elks-cancel-ongoing': {
      id: '/api/public/elks-cancel-ongoing'
      path: '/api/public/elks-cancel-ongoing'
      fullPath: '/api/public/elks-cancel-ongoing'
      preLoaderRoute: typeof ApiPublicElksCancelOngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicElksCancelOngoingRoute: ApiPublicElksCancelOngoingRoute,
  ApiPublicElksStatusRoute: ApiPublicElksStatusRoute,
  ApiPublicElksTestRoute: ApiPublicElksTestRoute,
  ApiPublicElksVoiceStartRoute: ApiPublicElksVoiceStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
