/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppKanbanRouteImport } from './routes/_app.kanban'
import { Route as AppCompaniesRouteImport } from './routes/_app.companies'
import { Route as AppCallsRouteImport } from './routes/_app.calls'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as ApiPublicElksVoiceStartRouteImport } from './routes/api/public/elks-voice-start'
import { Route as ApiPublicElksStatusRouteImport } from './routes/api/public/elks-status'
import { Route as ApiPublicElksConnectRouteImport } from './routes/api/public/elks-connect'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminInviteRouteImport } from './routes/_admin.admin.invite'
import { Route as AdminAdminEmployeesRouteImport } from './routes/_admin.admin.employees'
import { Route as AdminAdminEmployeeIdRouteImport } from './routes/_admin.admin.$employeeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ApiPublicElksVoiceStartRoute = ApiPublicElksVoiceStartRouteImport.update({
  id: '/api/public/elks-voice-start',
  path: '/api/public/elks-voice-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElksStatusRoute = ApiPublicElksStatusRouteImport.update({
  id: '/api/public/elks-status',
  path: '/api/public/elks-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElksConnectRoute = ApiPublicElksConnectRouteImport.update({
  id: '/api/public/elks-connect',
  path: '/api/public/elks-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminInviteRoute = AdminAdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminEmployeesRoute = AdminAdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminEmployeeIdRoute = AdminAdminEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/calls': typeof AppCallsRoute
  '/companies': typeof AppCompaniesRoute
  '/kanban': typeof AppKanbanRoute
  '/settings': typeof AppSettingsRoute
  '/admin/$employeeId': typeof AdminAdminEmployeeIdRoute
  '/admin/employees': typeof AdminAdminEmployeesRoute
  '/admin/invite': typeof AdminAdminInviteRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/api/public/elks-connect': typeof ApiPublicElksConnectRoute
  '/api/public/elks-status': typeof ApiPublicElksStatusRoute
  '/api/public/elks-voice-start': typeof ApiPublicElksVoiceStartRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/calls': typeof AppCallsRoute
  '/companies': typeof AppCompaniesRoute
  '/kanban': typeof AppKanbanRoute
  '/settings': typeof AppSettingsRoute
  '/admin/$employeeId': typeof AdminAdminEmployeeIdRoute
  '/admin/employees': typeof AdminAdminEmployeesRoute
  '/admin/invite': typeof AdminAdminInviteRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/api/public/elks-connect': typeof ApiPublicElksConnectRoute
  '/api/public/elks-status': typeof ApiPublicElksStatusRoute
  '/api/public/elks-voice-start': typeof ApiPublicElksVoiceStartRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_app/calls': typeof AppCallsRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_admin/admin/$employeeId': typeof AdminAdminEmployeeIdRoute
  '/_admin/admin/employees': typeof AdminAdminEmployeesRoute
  '/_admin/admin/invite': typeof AdminAdminInviteRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/api/public/elks-connect': typeof ApiPublicElksConnectRoute
  '/api/public/elks-status': typeof ApiPublicElksStatusRoute
  '/api/public/elks-voice-start': typeof ApiPublicElksVoiceStartRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/admin'
    | '/calls'
    | '/companies'
    | '/kanban'
    | '/settings'
    | '/admin/$employeeId'
    | '/admin/employees'
    | '/admin/invite'
    | '/admin/settings'
    | '/api/public/elks-connect'
    | '/api/public/elks-status'
    | '/api/public/elks-voice-start'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/calls'
    | '/companies'
    | '/kanban'
    | '/settings'
    | '/admin/$employeeId'
    | '/admin/employees'
    | '/admin/invite'
    | '/admin/settings'
    | '/api/public/elks-connect'
    | '/api/public/elks-status'
    | '/api/public/elks-voice-start'
    | '/admin'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/accept-invite'
    | '/login'
    | '/_admin/admin'
    | '/_app/calls'
    | '/_app/companies'
    | '/_app/kanban'
    | '/_app/settings'
    | '/_app/'
    | '/_admin/admin/$employeeId'
    | '/_admin/admin/employees'
    | '/_admin/admin/invite'
    | '/_admin/admin/settings'
    | '/api/public/elks-connect'
    | '/api/public/elks-status'
    | '/api/public/elks-voice-start'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  ApiPublicElksConnectRoute: typeof ApiPublicElksConnectRoute
  ApiPublicElksStatusRoute: typeof ApiPublicElksStatusRoute
  ApiPublicElksVoiceStartRoute: typeof ApiPublicElksVoiceStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/public/elks-voice-start': {
      id: '/api/public/elks-voice-start'
      path: '/api/public/elks-voice-start'
      fullPath: '/api/public/elks-voice-start'
      preLoaderRoute: typeof ApiPublicElksVoiceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elks-status': {
      id: '/api/public/elks-status'
      path: '/api/public/elks-status'
      fullPath: '/api/public/elks-status'
      preLoaderRoute: typeof ApiPublicElksStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elks-connect': {
      id: '/api/public/elks-connect'
      path: '/api/public/elks-connect'
      fullPath: '/api/public/elks-connect'
      preLoaderRoute: typeof ApiPublicElksConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/invite': {
      id: '/_admin/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminAdminInviteRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/employees': {
      id: '/_admin/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminAdminEmployeesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/$employeeId': {
      id: '/_admin/admin/$employeeId'
      path: '/$employeeId'
      fullPath: '/admin/$employeeId'
      preLoaderRoute: typeof AdminAdminEmployeeIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminEmployeeIdRoute: typeof AdminAdminEmployeeIdRoute
  AdminAdminEmployeesRoute: typeof AdminAdminEmployeesRoute
  AdminAdminInviteRoute: typeof AdminAdminInviteRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminEmployeeIdRoute: AdminAdminEmployeeIdRoute,
  AdminAdminEmployeesRoute: AdminAdminEmployeesRoute,
  AdminAdminInviteRoute: AdminAdminInviteRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCallsRoute: typeof AppCallsRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCallsRoute: AppCallsRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  ApiPublicElksConnectRoute: ApiPublicElksConnectRoute,
  ApiPublicElksStatusRoute: ApiPublicElksStatusRoute,
  ApiPublicElksVoiceStartRoute: ApiPublicElksVoiceStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
